// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// debugEncodedRString
void debugEncodedRString(SEXP str);
RcppExport SEXP _utf8StringsPkg_debugEncodedRString(SEXP strSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type str(strSEXP);
    debugEncodedRString(str);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_utf8StringsPkg_debugEncodedRString", (DL_FUNC) &_utf8StringsPkg_debugEncodedRString, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_utf8StringsPkg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
